### ISSUE TITLE
Doesn't build on CENTOS 6.5

### ISSUE THREAD

**Issue by davire** [gtk2hs/gtksourceview#2]
The build fails on Centos 6.5, with GHC 7.8.2
The epel repo is installed.
- The log is :

> Building gtksourceview2-0.13.1.3...
> Preprocessing library gtksourceview2-0.13.1.3...
> ./gtksourceview2.h:16:48: error: gtksourceview/gtksourceundomanager.h: No such file or directory
> ./gtksourceview2.h:17:51: error: gtksourceview/gtksourcecompletionitem.h: No such file or directory
> ./gtksourceview2.h:19:55: error: gtksourceview/gtksourcecompletionprovider.h: No such file or directory
> ./gtksourceview2.h:20:55: error: gtksourceview/gtksourcecompletionproposal.h: No such file or directory
> ./gtksourceview2.h:22:51: error: gtksourceview/gtksourcecompletioninfo.h: No such file or directory
> gtk2hsC2hs: Error during preprocessing
- gtksourceview2-devel-2.8.2-4.el6.x86_64 is installed : 
  it installs the following files in /usr/include/gtksourceview-2.0/gtksourceview :
  
  > gtksourcebuffer.h  gtksourceiter.h      gtksourcelanguagemanager.h  gtksourceprintcompositor.h  gtksourcestylescheme.h         gtksourceview.h
  > gtksourcegutter.h  gtksourcelanguage.h  gtksourcemark.h             gtksourcestyle.h            gtksourcestyleschememanager.h  gtksourceview-typebuiltins.h
- But the package needs :

```
#ifdef __BLOCKS__
#undef __BLOCKS__
#endif
#include "gtk2hs_macros.h"
#include <gtksourceview/gtksourcebuffer.h>
#if GTK_MAJOR_VERSION < 3
#include <gtksourceview/gtksourceiter.h>
#endif
#include <gtksourceview/gtksourcelanguage.h>
#include <gtksourceview/gtksourcelanguagemanager.h>
#include <gtksourceview/gtksourcestyle.h>
#include <gtksourceview/gtksourcestylescheme.h>
#include <gtksourceview/gtksourcestyleschememanager.h>
#include <gtksourceview/gtksourceview.h>
#include <gtksourceview/gtksourceview-typebuiltins.h>
#include <gtksourceview/gtksourceundomanager.h>
#include <gtksourceview/gtksourcecompletionitem.h>
#include <gtksourceview/gtksourcegutter.h>
#include <gtksourceview/gtksourcecompletionprovider.h>
#include <gtksourceview/gtksourcecompletionproposal.h>
#include <gtksourceview/gtksourcemark.h>
#include <gtksourceview/gtksourcecompletioninfo.h>
```

At this point I don't know what I can do to make this work.

**Comment by juhp** [comment]
I suspect that the C version of gtksourceview2 in EL6 is probably too old...
(I think ghc-gtksourceview2-0.11.1-1.el6 is in EPEL http://koji.fedoraproject.org/koji/buildinfo?buildID=207909)
